language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"

install:
  - "pip install -r requirements_dev.txt"

script:
  - "python setup.py install"
  - "py.test"

notifications:
  email:
    on_success: change
    on_failure: always
